### ISSUE TITLE
Replace `vm.assume` with `bound` in fuzz tests

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/example-native-token-transfers#431]
See test failure: https://github.com/wormhole-foundation/example-native-token-transfers/actions/runs/8836029057/job/24261632577?pr=399

From a contributor:
> It means the test threw out too many fuzz inputs for a particular test parameter. We should look into replacing vm.assume with bound if we can.

**Comment by kcsongor** [comment]
An instance of the failing test is
https://github.com/wormhole-foundation/example-native-token-transfers/blob/18f2663db661c02a9eb41a040cb9bf2e6e65fe19/evm/test/TrimmedAmount.t.sol#L191

in this case, the correct thing to do would be to set `b`'s decimals to be equal to that of `a`s instead of rejecting these cases. Replacing `assume` with `bound` is not applicable here (it would be if the assumes were used to reject out of bounds values -- in those cases bound is indeed better as it guides the random generator directly, making the process much more efficient).
