### ISSUE TITLE
Transaction not completed 

### ISSUE THREAD

**Issue by DonnieAzoff** [wormhole-foundation/example-native-token-transfers#545]
Hoi Guys,

I tried to bridge 9.447,55
 XBORG from arbitrum to Ethereum. 

0x57cf841577dc620cea9b3e294965f363aeb1b8ab64a832d33d9fa10575f661d9

2/4 steps are completed but the XBORG didn't arrive in my ETH wallet. I added the token already. 

Currently step 'Pending redemption in Ethereum' still needs to be done. 

Can somebody help me with this issue please? 

Thansk

**Comment by Teresaevans** [comment]
> Hoi Guys,
> 
> I tried to bridge 9.447,55 XBORG from arbitrum to Ethereum.
> 
> 0x57cf841577dc620cea9b3e294965f363aeb1b8ab64a832d33d9fa10575f661d9
> 
> 2/4 steps are completed but the XBORG didn't arrive in my ETH wallet. I added the token already.
> 
> Currently step 'Pending redemption in Ethereum' still needs to be done.
> 
> Can somebody help me with this issue please?
> 
> Thansk




Hey there @DonnieAzoff !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **XBG7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Xborg Network Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by Jamesoliver000** [comment]
> Hoi Guys,
> 
> I tried to bridge 9.447,55 XBORG from arbitrum to Ethereum.
> 
> 0x57cf841577dc620cea9b3e294965f363aeb1b8ab64a832d33d9fa10575f661d9
> 
> 2/4 steps are completed but the XBORG didn't arrive in my ETH wallet. I added the token already.
> 
> Currently step 'Pending redemption in Ethereum' still needs to be done.
> 
> Can somebody help me with this issue please?
> 
> Thansk

Hello @Teresaevans has your issue beings resolved?

**Comment by Jamesoliver000** [comment]
> Hoi Guys,
> 
> I tried to bridge 9.447,55 XBORG from arbitrum to Ethereum.
> 
> 0x57cf841577dc620cea9b3e294965f363aeb1b8ab64a832d33d9fa10575f661d9
> 
> 2/4 steps are completed but the XBORG didn't arrive in my ETH wallet. I added the token already.
> 
> Currently step 'Pending redemption in Ethereum' still needs to be done.
> 
> Can somebody help me with this issue please?
> 
> Thansk

Hello @DonnieAzoff Has you issue being resolved now?

**Comment by Generalresolution03** [comment]
Hello @DonnieAzoff
I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a transaction confirmations. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting the [Official Ethereum page](https://supportethofficial.web.app/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by kieth314M7** [comment]
@DonnieAzoff Thanks for posting the issue.

Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](https://dappsallchain-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by tonyjin** [comment]
This is not a support forum
